In [ ]:
import numpy as np

### 1. Create a 5×5 NumPy array filled with zeros. Then set the border to 1.

In [22]:
arr = np.zeros((5, 5))
arr[0, :] = 1
arr[4, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 2. Create a 1D array of numbers from 10 to 50 and reverse it.

In [24]:
arr_1d = np.arange(10, 51)
print(arr_1d[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. Generate a 3×3 identity matrix.

In [35]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4. Check if two NumPy arrays are equal:
a = np.array([1,2,3]), b = np.array([1,2,4])

In [43]:
a = np.array([1,2,3])
b = np.array([1,2,4])
print(a == b)

[ True  True False]


### 5. Replace all odd numbers in the array arr = np.arange(10) with -1.

In [56]:
array = np.arange(10)
array[array % 2 == 1] = -1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
