In [2]:
import numpy as np

### 1. Given a 4×4 matrix, extract the central 2×2 block.

In [5]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(arr[1:-1, 1:-1])



[[ 6  7]
 [10 11]]


### 2. Find the mean, median, and standard deviation of an array.

In [17]:
array = np.array([1,2,3,4,5,6,7,8,9])

print("Mean:",np.mean(array))
print("Median:",np.median(array))
print("Standard:",round(np.std(array)))

Mean: 5.0
Median: 5.0
Standard: 3


### 3. For array [10, 20, 30, 40], create an array where each element is squared minus 10.

In [27]:
arr = np.array([10, 20, 30, 40])
print(np.square(arr) - 10)

[  90  390  890 1590]


### 4. Use np.where() to find the indices of elements greater than 50 in an array.

In [40]:
array = np.array([30,40,50,55,60,70,80,90,100])
indices = np.where(array > 50)
print("Indices of element > 50:",indices[0])

Indices of element > 50: [3 4 5 6 7 8]


### 5. From a 2D matrix, extract rows where the sum is greater than 100.

In [58]:
arr = np.array([[10,15,25,35],
                [17,25,11,21],
                [40,10,25,35],
                [12,28,18,35]])

row_sum = np.sum(arr, axis=1)
mask = row_sum > 100
filtered_row = arr[mask]
print(filtered_row)

[[40 10 25 35]]
