In [1]:
import numpy as np

### 1. Multiply two 3×3 matrices using np.dot().

In [4]:
matrix_1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

matrix_2 = np.array([[1,4,7],
                     [2,5,8],
                     [3,6,9]])

print(np.dot(matrix_1, matrix_2))

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


### 2. Calculate the inverse and determinant of matrix:
A = np.array([[4,7],[2,6]])

In [6]:
A = np.array([[4,7],
              [2,6]])

inverse = np.linalg.inv(A)
determinant = np.linalg.det(A)

print("Inverse of A:\n",inverse,"\n")
print("Determinant of A:\n",determinant)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]] 

Determinant of A:
 10.000000000000002


### 3. Solve a linear equation:
Solve 2x + 3y = 8 and 3x + y = 5 using NumPy.

In [ ]:
A = np.array([[2, 3],
              [3, 1]])

B = np.array([8, 5])

x = np.linalg.solve(A, B)
print(x)

[1. 2.]


### 4. Use np.argmax() to find the index of the maximum row-wise and column-wise.

In [14]:
arr = np.array([
    [10, 50, 90],
    [70, 20, 60],
    [40, 80, 30]
])

column_wise = np.argmax(arr, axis=0)
row_wise = np.argmax(arr, axis=1)
print("Column Wise:",column_wise)
print("Row Wise:",row_wise)

Column Wise: [1 2 0]
Row Wise: [2 0 1]


### 5. Create a 5×5 matrix with row values increasing from 0 to 4.

In [24]:
array = np.tile(np.arange(5), (5, 1))
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
