In [3]:
import numpy as np

### 1. Create two arrays of shapes (5,1) and (1,4) and add them using broadcasting.

In [ ]:
arr_1 = np.array([[10],
                  [20],
                  [30],
                  [40],
                  [50]])

arr_2 = np.array([1,2,3,4])

broadcast = arr_1 + arr_2
print(broadcast)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]]


### 2. Simulate rolling a dice 1000 times using np.random.randint and find the frequency of each face.

In [17]:
faces = np.array([1,2,3,4,5,6])
roll_dice = np.random.randint(1, 7, 1000)
counts = np.bincount(roll_dice)[1:7]

for face, count in zip(faces,counts):
    print(f"{face} : {count}")

1 : 183
2 : 157
3 : 191
4 : 152
5 : 163
6 : 154


### 3. Create a matrix and normalize it (make all values between 0 and 1).

In [32]:
matrix = np.array([[11, 12, 13, 14],
                   [21, 22, 23, 24],
                   [31, 32, 33, 34],
                   [41, 42, 43, 44],
                   [51, 52, 53, 54]])

min_val = np.min(matrix)
max_val = np.max(matrix)

normalized = (matrix - min_val) / ( max_val - min_val)
print(normalized)

[[0.         0.02325581 0.04651163 0.06976744]
 [0.23255814 0.25581395 0.27906977 0.30232558]
 [0.46511628 0.48837209 0.51162791 0.53488372]
 [0.69767442 0.72093023 0.74418605 0.76744186]
 [0.93023256 0.95348837 0.97674419 1.        ]]


### 4. Generate a 4×4 matrix of random integers between 1 and 100. Replace values > 50 with 50.

In [43]:
matrix = np.random.randint(1, 100, size=(4,4))
print("Original Matrix:\n",matrix,"\n")
matrix[matrix > 50] = 50
print("Matrix where value > 50 = 50:\n",matrix)


Original Matrix:
 [[63  4 61 21]
 [ 4 12 17 25]
 [52 15 56 39]
 [85 65 99 93]] 

Matrix where value > 50 = 50:
 [[50  4 50 21]
 [ 4 12 17 25]
 [50 15 50 39]
 [50 50 50 50]]


### 5. Calculate cumulative sum and cumulative product of an array.

In [51]:
arr = np.array([[63, 34, 61, 21],
                [24, 12, 17, 25],
                [52, 15, 56, 39],
                [85, 65, 99, 93]])

cumulative_sum = np.cumsum(arr,axis=1)
cumulative_prod = np.cumprod(arr, axis=1)
print("Cumulative Sum:\n",cumulative_sum,"\n")
print("Cumulative product:\n",cumulative_prod)


Cumulative Sum:
 [[ 63  97 158 179]
 [ 24  36  53  78]
 [ 52  67 123 162]
 [ 85 150 249 342]] 

Cumulative product:
 [[      63     2142   130662  2743902]
 [      24      288     4896   122400]
 [      52      780    43680  1703520]
 [      85     5525   546975 50868675]]
