In [3]:
import numpy as np

### Basic Indexing (1D array)

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print("Element at index 0:", arr[0])
print("Element at index 3:", arr[3])
print("Last Element:", arr[-1])

Element at index 0: 10
Element at index 3: 40
Last Element: 50


### Basic Slicing (1D array)

In [5]:
arr = np.array([10,20,30,40,50,60,70,80,90])

# # From index 1 to 6
print("Basic Slicing:", arr[1:6])

# # From starts to index 3
print("From Start Slicing:", arr[:3])

# # From index 6 end
print("To End Slicing:", arr[6:])

# # From index 1 to 6 with step 2
print("Slicing with step:", arr[1:6:2])

# Reversed Array
print("Reversed array:", arr[::-1])

Basic Slicing: [20 30 40 50 60]
From Start Slicing: [10 20 30]
To End Slicing: [70 80 90]
Slicing with step: [20 40 60]
Reversed array: [90 80 70 60 50 40 30 20 10]


### Slicing 2D Arrays

In [6]:
arr_2d = np.array([[10,20,30],
                   [40,50,60],
                   [70,80,90]])

# Find Specific element in 2D Array
print("Specific element:", arr_2d[1, 2])  # row [1] & index [2] => 60

# Entire row
print("Entire row:", arr_2d[1, :])  # row [1] & All Columns => [40 50 60]

# Entire Column
print("Entire Column:", arr_2d[:,1])  # All rows & Column [1] => [20 50 80]

# Specific Array
print("Specific Array:\n", arr_2d[0:2, 1:])  # From row[0] to [1] & Column[1] to [end] =>  [[20 30],[50 60]]

Specific element: 60
Entire row: [40 50 60]
Entire Column: [20 50 80]
Specific Array:
 [[20 30]
 [50 60]]


### Sorting Array

In [7]:
# 1D Array Sorting
unsorted_arr = np.array([9,1,8,3,7,2,4,6,5])
print("Sorted Array:",np.sort(unsorted_arr),"\n")

# 2D Array Sorting
arr2d_unsorted = np.array([[3,1],
                           [2,3],
                           [1,2]])
print("Sorted 2D Array by Column:\n",np.sort(arr2d_unsorted, axis=0),"\n")
print("Sorted 2D Array by row:\n",np.sort(arr2d_unsorted, axis=1))


Sorted Array: [1 2 3 4 5 6 7 8 9] 

Sorted 2D Array by Column:
 [[1 1]
 [2 2]
 [3 3]] 

Sorted 2D Array by row:
 [[1 3]
 [2 3]
 [1 2]]


### Filtering Array

In [8]:
# Filtering Even numbers from Array
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = numbers[numbers % 2 == 0]  # expression
print("Even Numbers:",even_number)

Even Numbers: [ 2  4  6  8 10]


### Filtering with Mask

In [9]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

mask = numbers > 5
# print("mask:",mask)
print("Numbers Greater than 5:",numbers[mask])   # expression 

Numbers Greater than 5: [ 6  7  8  9 10]


### Combine Conditions

In [10]:
arr = np.array([10, 15, 20, 25, 30])

filtered = arr[(arr > 15) & (arr <= 25)]
print("Filtered Array:",filtered)

Filtered Array: [20 25]


### Masking in 2D Arrays

In [11]:
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30]])

mask = arr2d >= 20
print("Mask:\n",mask,"\n")

print("Filtered:\n",arr2d[mask])

Mask:
 [[False False False]
 [ True  True  True]] 

Filtered:
 [20 25 30]


### Fancy Indexing

In [12]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

indices = [0, 4, 7]  # 0th, 4th, & 7th position of numbers
print("Indices:",numbers[indices],"\n")

# Using "Where"
where_result = np.where(numbers > 5)    # expression 
print("Where numbers greater than 5:",numbers[where_result])

Indices: [1 5 8] 

Where numbers greater than 5: [ 6  7  8  9 10]


 It works like this--
 if numbers > 5:
     numbers * 2
 else:
     numbers

In [13]:
condition_arr = np.where(numbers > 5, numbers*2, numbers)
print("Output:",condition_arr)

Output: [ 1  2  3  4  5 12 14 16 18 20]


### Concatenate Array

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combine = np.concatenate((arr1, arr2))
print("Concatenated Array:",combine)

Concatenated Array: [1 2 3 4 5 6]


### Array Compatibility

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

print("Compatibility shape:", arr1.shape == arr2.shape)

Compatibility shape: True


### Add Array Vertically

In [16]:
org_array = np.array([[1,2],
                     [3,4]])

new_row = np.array([[5,6]])

add_vertical = np.vstack((org_array, new_row))

print("Original Array:\n",org_array,"\n")
print("with new Row:\n",add_vertical)

Original Array:
 [[1 2]
 [3 4]] 

with new Row:
 [[1 2]
 [3 4]
 [5 6]]


### Add Array Horizontally

In [17]:
org_array = np.array([[1,2],
                     [3,4]])

new_column = np.array([[5],[6]])

add_vertical = np.hstack((org_array, new_column))

print("Original Array:\n",org_array,"\n")
print("with new Column:\n",add_vertical)

Original Array:
 [[1 2]
 [3 4]] 

with new Column:
 [[1 2 5]
 [3 4 6]]


### Delete Element in Array

In [18]:
arr = np.array([1,2,3,4,5,6])

delete = np.delete(arr, 2)
print("Array after deletion: ",delete)

Array after deletion:  [1 2 4 5 6]
