In [ ]:
import numpy as np

### Save array to a file

In [6]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

np.savetxt("my_array.csv", data, delimiter=',', fmt='%d')
print("Array Saved Successfully!")

Array Saved Successfully!


###  Load array from a file

In [7]:
load_data = np.loadtxt("my_array.csv", delimiter=',', dtype=int)
print("Loaded Data:\n",load_data)

Loaded Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Load Data using np.genfromtxt()

In [9]:
# Better than loadtxt() for missing/dirty data
# Handles missing values (like ,,)
# Allows mixed datatypes (like strings + numbers)
# Better for real-world messy .csv files

data = np.genfromtxt("my_array.csv", defaultfmt=',', dtype=None, encoding="utf-8", skip_header=1)
print(data)

['4,5,6' '7,8,9']


### Save & Load Binary Data    

In [14]:
arr = np.arange(1, 10).reshape(3, 3)

# save Data
np.save("my_data.npy", arr)
print("Data Saved Successfully!\n")

# load Data
data = np.load("my_data.npy")
print("Data Loaded Successfully!\n",data)

Data Saved Successfully!

Data Loaded Successfully!
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Save multiple arrays together

In [21]:
arr_1 = np.arange(7, 16).reshape(3, 3)
arr_2 = np.arange(3, 12).reshape(3, 3)

np.savez("multiple_arrays.npz", a=arr_1, b=arr_2)
print("Multiple Arrays Saved Successfully!\n")

load_multi_array = np.load("multiple_arrays.npz")
print("Array 1:\n",load_multi_array["a"],"\n")
print("Array 2:\n",load_multi_array["b"])

Multiple Arrays Saved Successfully!

Array 1:
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]] 

Array 2:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
